spring:
  application:
    name: productservice
  datasource:
    url: jdbc:postgresql://localhost:5432/product
    username: mahesh
    password: mahesh
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8081
